#!/usr/bin/env sh

# cd to the root of the git repo
cd "$(git rev-parse --show-toplevel)" || return

SELECTED_PATH=$(git status --porcelain | grep -E '^(M|M | M|\?\?)' | awk '{print $2}' | fzf)

# if no path was selected, return
if [ -z "$SELECTED_PATH" ]; then
	return
fi

# open the selected file in nvim
nvim "$SELECTED_PATH"
