#!/usr/bin/env sh

# cd to the root of the git repo
cd "$(git rev-parse --show-toplevel)" || exit

SELECTED_PATH=$(git status --porcelain | grep -E '^(M|M | M)' | awk '{print $2}' | fzf)

# if no path was selected, exit
if [ -z "$SELECTED_PATH" ]; then
	exit
fi

# restore the selected path
git restore "$SELECTED_PATH"
printf "Restored %s\n" "$SELECTED_PATH"
