#!/usr/bin/env sh

SELECTED_PATH=$( (
	fd . ~/ ~/Documents ~/Downloads ~/test
	echo ~/Documents
	echo ~/Downloads
	echo ~/test
) | fzf)

# if no path was selected, exit
if [ -z "$SELECTED_PATH" ]; then
	exit
fi

# if the selected path is a file, cd to the directory it is in
if [ -f "$SELECTED_PATH" ]; then
	cd "$(dirname "$SELECTED_PATH")" || exit
fi

# if the selected path is a directory, cd to it
if [ -d "$SELECTED_PATH" ]; then
	cd "$SELECTED_PATH" || exit
fi

# open the selected path in nvim
nvim "$SELECTED_PATH"
