#!/usr/bin/env sh

START_PATH=$(pwd)
SELECTED_PATH=$(git status --porcelain | grep -E '^(M|M | M|\?\?)' | fzf | awk '{print $2}')

# if no path was selected, return
if [ -z "$SELECTED_PATH" ]; then
	return
fi

# cd to the root of the git repo and open the selected file in nvim
cd "$(git rev-parse --show-toplevel)" || return
nvim "$SELECTED_PATH"

# cd back to the start path
cd "$START_PATH" || return
