#!/usr/bin/env sh

SELECTED_PATH=$( (
	fd . ~/ ~/Documents ~/Downloads
	echo ~/Documents
	echo ~/Downloads
) | fzf)

# if no path was selected, return
if [ -z "$SELECTED_PATH" ]; then
	return
fi

# if the selected path is a file, cd to the directory it is in and then to the
# git root
if [ -f "$SELECTED_PATH" ]; then
	cd "$(dirname "$SELECTED_PATH")" || return
	cd "$(git rev-parse --show-toplevel)" || return
fi

# if the selected path is a directory, cd to it and then to the git root
if [ -d "$SELECTED_PATH" ]; then
	cd "$SELECTED_PATH" || return
	cd "$(git rev-parse --show-toplevel)" || return
fi

# open the selected path in nvim
nvim "$SELECTED_PATH"
