#!/usr/bin/env sh

SELECTED_PATH=$( (
	fd . ~/ ~/Documents ~/Downloads ~/test ~/iCloud
	echo ~/Documents
	echo ~/Downloads
	echo ~/test
	echo ~/iCloud
) | fzf)

# if no path was selected, return
if [ -z "$SELECTED_PATH" ]; then
	return
fi

# if the selected path is a file, cd to the directory it is in and then to the
# git root
if [ -f "$SELECTED_PATH" ]; then
	cd "$(dirname "$SELECTED_PATH")" || return
	cd "$(git rev-parse --show-toplevel)" || return
fi

# if the selected path is a directory, cd to it and then to the git root
if [ -d "$SELECTED_PATH" ]; then
	cd "$SELECTED_PATH" || return
	cd "$(git rev-parse --show-toplevel)" || return
fi

# open the selected path in nvim or use open command for other files
PATH_EXTENSION="${SELECTED_PATH##*.}"

for EXTENSION in pdf xlsx xls ppt pptx doc docx jpg jpeg png; do
	if [ "$PATH_EXTENSION" = "$EXTENSION" ]; then
		open "$SELECTED_PATH"
		return
	fi
done

nvim "$SELECTED_PATH"
