#!/usr/bin/env sh

start_path=$(pwd)
selected_path=$(
	fd -u . ~/ \
		-E Library \
		-E node_modules \
		-E .vscode \
		-E .git \
		-E .cache \
		-E .config/cargo \
		-E .config/rustup \
		-E Public \
		-E Pictures \
		-E Music \
		-E Movies \
		-E .DS_Store \
		-E target \
		-E .local \
		-E .npm |
		fzf
)

# if path is a file, open it in nvim
if [ -f "$selected_path" ]; then
	cd "$(dirname "$selected_path")" || exit
	cd "$(git rev-parse --show-toplevel)" || exit
	nvim "$selected_path"
	cd "$start_path" || exit
fi

# if path is a directory, open nvim on it
if [ -d "$selected_path" ]; then
	cd "$selected_path" || exit
	cd "$(git rev-parse --show-toplevel)" || exit
	nvim "$selected_path"
	cd "$start_path" || exit
fi
