#!/usr/bin/env sh

SELECTED_PATH=$( (
	fd . ~/ ~/Documents ~/Downloads
	echo ~/Documents
	echo ~/Downloads
) | fzf)

# if path is a file, open it in nvim
if [ -f "$SELECTED_PATH" ]; then
	cd "$(dirname "$SELECTED_PATH")" || exit
	cd "$(git rev-parse --show-toplevel)" || exit
	nvim "$SELECTED_PATH"
fi

# if path is a directory, open nvim on it
if [ -d "$SELECTED_PATH" ]; then
	cd "$SELECTED_PATH" || exit
	cd "$(git rev-parse --show-toplevel)" || exit
	nvim "$SELECTED_PATH"
fi
