#!/usr/bin/env sh

start_path=$(pwd)
selected_path=$( (
	fd . ~/ ~/Documents ~/Downloads
	echo ~/Documents
	echo ~/Downloads
) | fzf)

# if path is a file, open it in nvim
if [ -f "$selected_path" ]; then
	cd "$(dirname "$selected_path")" || exit
	nvim "$selected_path"
	cd "$start_path" || exit
fi

# if path is a directory, open nvim on it
if [ -d "$selected_path" ]; then
	cd "$selected_path" || exit
	nvim "$selected_path"
	cd "$start_path" || exit
fi
