#!/usr/bin/env sh

START_PATH=$(pwd)
SELECTED_PATH=$(
	fd -u . ~/ \
		-E Library \
		-E node_modules \
		-E .vscode \
		-E .git \
		-E .cache \
		-E .config/cargo \
		-E .config/rustup \
		-E Public \
		-E Pictures \
		-E Music \
		-E Movies \
		-E .DS_Store \
		-E target \
		-E .local \
		-E .npm |
		fzf
)

# if no path was selected, return
if [ -z "$SELECTED_PATH" ]; then
	return
fi

# if the selected path is a file, cd to the directory it is in
if [ -f "$SELECTED_PATH" ]; then
	cd "$(dirname "$SELECTED_PATH")" || return
fi

# if the selected path is a directory, cd to it
if [ -d "$SELECTED_PATH" ]; then
	cd "$SELECTED_PATH" || return
fi

# open the selected path in nvim and later cd back to the start path
nvim "$SELECTED_PATH"
cd "$START_PATH" || return
