#!/usr/bin/env sh

start_dir=$(pwd)
selected_file=$(fd -t d . ~/ ~/Documents ~/Downloads | fzf)
selected_dir=$(dirname "$selected_file")

if [ -n "$selected_file" ]; then
	cd "$selected_dir" || exit
	root_dir=$(git rev-parse --show-toplevel)
	cd "$root_dir" || exit
	nvim "$selected_file"
	cd "$start_dir" || exit
fi
