#!/usr/bin/env sh

START_PATH=$(pwd)
SELECTED_PATH=$(
	fd -u . ~/ \
		-E Library \
		-E node_modules \
		-E .vscode \
		-E .git \
		-E .cache \
		-E .config/cargo \
		-E .config/rustup \
		-E Public \
		-E Pictures \
		-E Music \
		-E Movies \
		-E .DS_Store \
		-E target \
		-E .local \
		-E .npm |
		fzf
)

# if path is a file, open it in nvim
if [ -f "$SELECTED_PATH" ]; then
	cd "$(dirname "$SELECTED_PATH")" || exit
	cd "$(git rev-parse --show-toplevel)" || exit
	nvim "$SELECTED_PATH"
	cd "$START_PATH" || exit
fi

# if path is a directory, open nvim on it
if [ -d "$SELECTED_PATH" ]; then
	cd "$SELECTED_PATH" || exit
	cd "$(git rev-parse --show-toplevel)" || exit
	nvim "$SELECTED_PATH"
	cd "$START_PATH" || exit
fi
