#!/usr/bin/env sh

start_path=$(pwd)
selected_path=$(git status --porcelain | grep -E '^(M|M | M|\?\?)' | fzf | awk '{print $2}')

if [ -n "$selected_file" ]; then
	nvim "$selected_path"
	cd "$start_path" || exit
fi
