#!/usr/bin/env sh

RG_PREFIX="rg  --column --line-number --no-heading --color=always --smart-case --colors 'match:fg:200,200,200' --colors 'path:fg:blue' --colors 'line:fg:yellow'"

fzf --ansi --disabled \
	--bind "start:reload:$RG_PREFIX {q} ." \
	--bind "change:reload:sleep 0; $RG_PREFIX {q} || true" \
	--bind "ctrl-p:unbind(change,alt-enter)+change-prompt(2. fzf> )+enable-search+clear-query" \
	--color "hl:-1:underline,hl+:-1:underline:reverse" \
	--prompt '1. ripgrep> ' \
	--delimiter : \
	--preview 'bat --color=always {1} --highlight-line {2}' \
	--preview-window '+{2}+3/3,~3' \
	--bind 'enter:become(nvim {1} +{2})'
