#!/usr/bin/env sh

RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case --colors 'match:fg:green' --colors 'path:fg:blue' --colors 'line:fg:yellow'"

fzf --ansi --disabled \
	--bind "start:reload:$RG_PREFIX {q}  ~/ ~/Documents ~/Downloads ~/test ~/iCloud" \
	--bind "change:reload:sleep 0; $RG_PREFIX {q} ~/ ~/Documents ~/Downloads ~/test ~/iCloud || true" \
	--bind "ctrl-p:unbind(change,alt-enter)+change-prompt(2. fzf> )+enable-search+clear-query" \
	--color "hl:green,hl+:green" \
	--prompt '1. ripgrep> ' \
	--delimiter : \
	--preview 'bat --color=always {1} --highlight-line {2}' \
	--preview-window '+{2}+3/3,~3' \
	--bind 'enter:become(nvim {1} +{2})'
