#!/usr/bin/env sh

SELECTED_PATH=$( (
	fd . ~/ ~/Documents ~/Downloads ~/dev ~/iCloud
	echo ~/Documents
	echo ~/Downloads
	echo ~/dev
	echo ~/iCloud
) | fzf)

# if no directory is selected, exit
if [ -z "$SELECTED_PATH" ]; then
	return
fi

# if the selected path is a file, cd to the directory it is in
if [ -f "$SELECTED_PATH" ]; then
	cd "$(dirname "$SELECTED_PATH")" || return
fi

# if the selected path is a directory, cd to it
if [ -d "$SELECTED_PATH" ]; then
	cd "$SELECTED_PATH" || return
fi
